### ISSUE TITLE
User presets for instruments

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#125]
Most of the time, I do not rebuild complex stacks from scratch, but rather start off from a certain "basic" version of my instruments. It would be super convenient to be able to select them from a drop-down, similar to the built-in presets.

The feature could be configurable over `~/.config/sointu/presets.yml`. This file could have the structure
```yml
presets:
 - name: Single instrument
   location: /path/to/single_instrument.yml
 - name: Instrument in patch
   location: /path/to/patch.yml:instrument_name_in_patch
```

The tracker could display a button (or have a menu entry) to make the current instrument a preset automatically (by adding it to `presets.yml`).
