### ISSUE TITLE
Native tracker and plugin hard crash when drag-reordering, deleting or disabling certain instruments

### ISSUE THREAD

**Issue by LeStahL** [vsariola/sointu#149]
This problem is weird - the musician experienced weird native tracker and plugin hard crashes when editing stacks. I boiled the instrument down to this minimal example:
```yml
name: rp-Berlin
numvoices: 7
units:
    - type: oscillator
      id: 2
      parameters: {attack: 64, color: 42, decay: 64, detune: 74, gain: 128, looplength: 563, loopstart: 5448, phase: 0, release: 64, samplestart: 143113, shape: 82, stereo: 1, sustain: 64, transpose: 69, type: 4, unison: 1}
    - type: out
      id: 11
      parameters: {auxgain: 64, color: 64, damp: 0, detune: 64, dry: 128, feedback: 96, gain: 64, notetracking: 2, outgain: 64, phase: 0, pregain: 40, shape: 64, stereo: 1, transpose: 64, type: 0}
```
When disabling or deleting either of the units, the native tracker (and plugin) hard-crash. I collected debug output as well:
[sointu_crashlog2.log](https://github.com/user-attachments/files/17016893/sointu_crashlog2.log)

**Comment by LeStahL** [comment]
It must be somehow connected to the gm.dls sampler - I can't reproduce with the trisaw oscillator

**Comment by vsariola** [comment]
Uh wait what happen? Why does that oscillator have attack and decay???

**Comment by vsariola** [comment]
The fact that the unit parameter maps have gotten messed up is worrying, but it is most likely unrelated to this problem. I narrowed the problem down to stereo oscillator + multiple voices + sample based oscillators.

**Comment by LeStahL** [comment]
will try and reproduce with mono

**Comment by LeStahL** [comment]
this instrument has only mono units. reproduce by drag-reordering oscillator or send unit anywhere:
```yml
units:
- type: oscillator
  id: 3
  parameters: {attack: 64, color: 64, decay: 64, detune: 64, gain: 64, looplength: 5976, loopstart: 7, phase: 0, release: 64, samplestart: 441930, shape: 64, stereo: 0, sustain: 64, transpose: 38, type: 4}
- type: delay
  id: 5
  parameters: {color: 64, damp: 0, detune: 64, dry: 128, feedback: 96, gain: 64, notetracking: 2, phase: 0, pregain: 40, shape: 64, stereo: 0, transpose: 64, type: 0}
  varargs: [48]
- type: send
  id: 4
  parameters: {amount: 128, color: 64, detune: 64, gain: 64, panning: 64, phase: 0, port: 0, sendpop: 1, shape: 64, stereo: 0, target: 3, transpose: 64, type: 0, unit: 0, voice: 0}

```
